title: The Physics of Product‑Market Fit
description: A practical field guide to overcoming status‑quo inertia and reaching adoption.
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 2..3
plugins:
  - jekyll-seo-tag
permalink: pretty
theme: null
exclude:
  - node_modules
  - vendor
